# Deploy to AWS App Runner via ECR
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: us-east-1

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ECR_REPOSITORY_URI }}:latest .

    - name: Push Docker image to Amazon ECR
      run: |
        docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest

    - name: Deploy to AWS App Runner
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
      run: |
        aws apprunner update-service \
          --service-name ${{ secrets.APP_RUNNER_SERVICE_NAME }} \
          --source-configuration ImageRepositoryConfiguration={
            ImageIdentifier=${{ secrets.ECR_REPOSITORY_URI }}:latest,
            ImageRepositoryType=ECR
          }

